### ISSUE TITLE
Structuring the code in pythonic way

### ISSUE THREAD

**Issue by navyad** [TC01/python-xkcd#9]
Its a python library, i guess we can use the python naming conventions for class, functions etc.  And would be better if we follow python coding style formerly know as PEP-8.

 @TC01 will create PR for this.

**Comment by TC01** [comment]
Feel free to open a PR-- I'm always happy to see interest in one of my projects, especially a small side project like this one that is more or less "complete" (as far as I am concerned, anyway). 

That being said... while I'd consider such a patch with an open mind, I should warn you now that I will be rather reluctant to merge API breaking changes (not that this has much of an API, or, to be honest, a well-thought-out one, but still-- I am using it another project) just for the sake of being slightly more Pythonic.

And I am curious what conventions you are referring to that aren't being applied correctly?

Also:

> And would be better if we follow python coding style formerly know as PEP-8.

I should warn you that I do not approve of (and will not merge) at least two PEP-8-isms:

* The use of spaces instead of tabs. (But I can fix this manually on merging any patches)

* The limitation of code to 80 characters a line.  (I would concede that code should be line-wrapped at some point, but I'm not always consistent at where I do it. These days, I'd probably say 120 is a good guideline).

**Comment by TC01** [comment]
> That being said... while I'd consider such a patch with an open mind, I should warn you now that I will be rather reluctant to merge API breaking changes (not that this has much of an API, or, to be honest, a well-thought-out one, but still-- I am using it another project) just for the sake of being slightly more Pythonic.

Though I should add that we can, obviously, get around this with DeprecationWarnings depending on what it is you think should be changed.

**Comment by navyad** [comment]
@TC01 
Following are my suggested structural changes or _pythonic_ code:
-- naming of some functions is camleCase, wen can make them snake_case.
-- removing PEP-8 errors.

Although at the back of my mind i have this design concern which is:
-- some of the methods which should be part of the class are defined as free methods. 
e.g. getWhatIfArchive() should be part of class WhatIf.

Let me know you thoughts, thanks.

**Comment by TC01** [comment]
> -- naming of some functions is camleCase, wen can make them snake_case.

Ah. While it's true that this is the preferred style, PEP8 has this to say about naming and camelCase naming for functions:

> mixedCase is allowed only in contexts where that's already the prevailing style (e.g. threading.py), to retain backwards compatibility.

That's the case here, so I don't think it makes much sense to change it now. If you really, really wanted to use underscore naming instead of camelCase, there would be two ways to do it, and I personally don't think either is worth the effort:

* Break all API compatibility and rename all the functions. This would be a clean "fix", but at the cost of breaking API compatibility. If you haven't gotten the idea yet, I care a great deal about API compatibility. :) I don't know if anyone other than me actually uses this module for anything, but I would be rather annoyed if a small module I was using suddenly changed the way all its functions were invoked in a not-backwards-compatible way. (Especially one that claims to be "Stable").

* Rename all the functions, and then provide deprecation warning wrappers with the old names. This could be done, but it would involve more or less doubling the number of methods in the module for little benefit. Also, this would mean there would be two ways to invoke more or less every function in the library, which [isn't very Pythonic either](https://www.python.org/dev/peps/pep-0020/).

> -- removing PEP-8 errors.(excluding the ones you mentioned)

Sure; this is fine with me. :)

> Although at the back of my mind i have this design concern which is:
-- some of the methods which should be part of the class are defined as free methods. 
e.g. getWhatIfArchive() should be part of class WhatIf.

Well, the class WhatIf is actually representing a *single* WhatIf article (in the same way the class Comic represents a single Comic object, not the xkcd Comic itself). Maybe the name "Article" would have been better, but "What If" seems to be a relatively common way to refer to the individual articles themselves. Anyway, getWhatIfArchive() returns a collection of WhatIf objects, which is why I didn't put that method in a class. Does that make sense to you, or do you think this is incorrect?

We could have a WhatIf class with all the WhatIf-related helper functions and a WhatIfArticle class that is the *current* WhatIf class, but this seems like an unnecessary use of classes to me.

**Comment by navyad** [comment]
While the changes for the naming of the functions, i understand you point of backward compatibility.
As for
> 
Well, the class WhatIf is actually representing a single WhatIf article (in the same way the class Comic represents a single Comic object, not the xkcd Comic itself). Maybe the name "Article" would have been better, but "What If" seems to be a relatively common way to refer to the individual articles themselves. Anyway, getWhatIfArchive() returns a collection of WhatIf objects, which is why I didn't put that method in a class. Does that make sense to you, or do you think this is incorrect?

Its not incorrect at all but if a class is defined all its related behavior should be encapsulated within a class itself, as per my opinion. 

```
class Whatif:

 @classmethod:
 def getWhatIfArchive():
     # return objects
```

**Comment by TC01** [comment]
Well, this is a year+ old now, but...

> Its not incorrect at all but if a class is defined all its related behavior should be encapsulated within a class itself, as per my opinion.

I suppose you could argue that this is more elegant, but I don't think it particularly matters for a project this small. But to me it feels like bikeshedding.

Anyway, I am going to close this ticket, since it's old, but if you are still interested in cleanup changes, you're welcome to file PRs. Though, as I said before, I don't really see the need to break compatibility by moving functions around or renaming them (especially for such a small module).
